spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: ssa_admin
    password: dba
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
    hibernate: 
      ddl-auto: update
      